name: Question
description: Ask a question about usage or architecture
title: "[Question] "
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
